services:

  app:
    container_name: api
    image: alexbaratieri/laravel-app:10
    restart: unless-stopped
    environment:
      USER: ${SYS_USER-www-data}
      UID: ${SYS_UID-1000}
    working_dir: /var/www/
    volumes:
      - ./app/:/var/www
      - ./configs/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - api

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT-80}:80
    volumes:
      - ./app/:/var/www
      - ./configs/nginx/local.conf:/etc/nginx/conf.d/default.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - api

  mysql:
    container_name: mysql
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD-secret}
      MYSQL_USER: ${DB_USERNAME-laravel}
      TZ: ${DB_TIMEZONE-America/Sao_Paulo}
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./configs/mysql/init:/docker-entrypoint-initdb.d/:rw
      - ./configs/mysql/my.cnf:/etc/my.cnf
    ports:
      - 172.17.0.1:${DB_PORT-3306}:3306
    networks:
      - api

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file: .env
    ports:
      - 172.17.0.1:${REDIS_PORT-6379}:6379
    networks:
      - api

volumes:
  mysql-data:
    name: 'mysql-data'

networks:
  api:
    driver: bridge
