name: Run Tests (SQLite In-Memory)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Copy environment file
        run: cp .env.example .env
        working-directory: app/

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: app/

      - name: Generate app key
        run: php artisan key:generate
        working-directory: app/

      - name: Run migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan migrate --force
        working-directory: app/

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: vendor/bin/phpunit
        working-directory: app/
